# Generated by Django 3.2.4 on 2021-07-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_info_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketinfomodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
