# Generated by Django 3.2.4 on 2021-06-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValueInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('town', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('text', models.TextField(max_length=300)),
            ],
        ),
    ]
