# Generated by Django 3.2.4 on 2021-07-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_valueinquiry_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ValueInquiry',
            new_name='Inquiry',
        ),
    ]
