# Generated by Django 3.2.4 on 2021-07-08 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0003_rename_valueinquiry_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('покупка/продажба', 'покупка/продажба'), ('наема/отдава под наем', 'наема/отдава под наем'), ('пазарна оценка', 'пазарна оценка'), ('друго', 'друго')], max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='inquiry',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inquiry.categorymodel'),
        ),
    ]
