# Generated by Django 3.2.4 on 2021-07-08 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0004_auto_20210708_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
