# Generated by Django 3.2.4 on 2021-07-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0005_inquiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
