# Generated by Django 3.2.4 on 2021-07-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0007_alter_inquiry_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='category',
            field=models.CharField(choices=[('покупка/продажба', 'покупка/продажба'), ('наема/отдава под наем', 'наема/отдава под наем'), ('пазарна оценка', 'пазарна оценка'), ('друго', 'друго')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
