# Generated by Django 3.2.4 on 2021-08-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0009_auto_20210806_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='first_name',
            field=models.CharField(max_length=15),
        ),
    ]
