# Generated by Django 3.2.4 on 2021-06-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TownModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Plovdiv', 'Plovdiv'), ('Sofia', 'Sofia'), ('Varna', 'Varna')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'town',
            },
        ),
        migrations.CreateModel(
            name='TypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('One room', 'One room'), ('Two rooms', 'Two rooms'), ('Three rooms', 'Three rooms')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'type',
            },
        ),
        migrations.CreateModel(
            name='ApartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.PositiveIntegerField()),
                ('year', models.IntegerField()),
                ('furnishing', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=200)),
                ('town', models.ManyToManyField(to='apart_app.TownModel')),
                ('type', models.ManyToManyField(to='apart_app.TypeModel')),
            ],
        ),
    ]
