# Generated by Django 3.2.4 on 2021-06-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart_app', '0003_alter_townmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typemodel',
            name='name',
            field=models.CharField(choices=[('Едностаен', 'Есностаен'), ('Двустаен', 'Двустаен'), ('Тристаен', 'Тристаен')], max_length=20),
        ),
    ]
