# Generated by Django 3.2.4 on 2021-06-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart_app', '0004_alter_typemodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmodel',
            old_name='area',
            new_name='pure_area',
        ),
        migrations.AddField(
            model_name='apartmodel',
            name='district',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartmodel',
            name='total_area',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
