# Generated by Django 3.2.4 on 2021-06-28 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apart_app', '0006_personmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonModel',
        ),
        migrations.AlterModelOptions(
            name='townmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='typemodel',
            options={},
        ),
    ]
