# Generated by Django 3.2.4 on 2021-07-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart_app', '0007_auto_20210628_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartFilterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(choices=[('Plovdiv', 'Пловдив'), ('Sofia', 'София'), ('Varna', 'Варна')], max_length=20)),
                ('type', models.CharField(choices=[('one_room', 'Есностаен'), ('two_rooms', 'Двустаен'), ('three_rooms', 'Тристаен')], max_length=20)),
                ('construction', models.CharField(choices=[('panel', 'панел'), ('monolith', 'монолит'), ('epk', 'ЕПК')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('panel', 'панел'), ('monolith', 'монолит'), ('epk', 'ЕПК')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DealModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('buy', 'купува'), ('sell', 'продава'), ('lease', 'дава под наем'), ('rent', 'търси да наеме')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FinishingWorksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('done', 'изпълнени'), ('not_done', 'на шпакловка и замазка')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FurnishingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('furnishing', 'обзаведен'), ('without_furnishing', 'необзаведен')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('active', 'активна обява'), ('not_active', 'неактивна обява/продадена')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='townmodel',
            name='name',
            field=models.CharField(choices=[('Plovdiv', 'Пловдив'), ('Sofia', 'София'), ('Varna', 'Варна')], max_length=20),
        ),
        migrations.AlterField(
            model_name='typemodel',
            name='name',
            field=models.CharField(choices=[('one_room', 'Есностаен'), ('two_rooms', 'Двустаен'), ('three_rooms', 'Тристаен')], max_length=20),
        ),
    ]
