# Generated by Django 3.2.4 on 2021-07-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apart_app', '0008_auto_20210706_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartfiltermodel',
            name='construction',
        ),
    ]
