# Generated by Django 3.2.4 on 2021-07-06 10:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apart_app', '0009_remove_apartfiltermodel_construction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction_year', models.CharField(blank=True, max_length=4)),
                ('price_offer', models.PositiveIntegerField()),
                ('price_realized', models.PositiveIntegerField()),
                ('pure_area', models.PositiveIntegerField()),
                ('total_area', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=200)),
                ('image_url', models.URLField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('email', models.EmailField(max_length=254)),
                ('counter_seen', models.IntegerField(default=0)),
                ('construction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apart_app.constructionmodel')),
                ('deal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apart_app.dealmodel')),
                ('finishing_works', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apart_app.finishingworksmodel')),
                ('furnishing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apart_app.furnishingmodel')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apart_app.statusmodel')),
                ('town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apart_app.townmodel')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apart_app.typemodel')),
            ],
        ),
    ]
