# Generated by Django 3.2.4 on 2021-07-06 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart_app', '0010_apartmentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartfiltermodel',
            name='town',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='apartfiltermodel',
            name='type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='apartmentmodel',
            name='counter_seen',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='apartmentmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='apartmentmodel',
            name='price_realized',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
