# Generated by Django 3.2.4 on 2021-07-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart_app', '0011_auto_20210706_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionmodel',
            name='name',
            field=models.CharField(choices=[('панел', 'панел'), ('монолит', 'монолит'), ('ЕПК', 'ЕПК')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dealmodel',
            name='name',
            field=models.CharField(choices=[('купува', 'купува'), ('продава', 'продава'), ('дава под наем', 'дава под наем'), ('търси да наеме', 'търси да наеме')], max_length=20),
        ),
        migrations.AlterField(
            model_name='finishingworksmodel',
            name='name',
            field=models.CharField(choices=[('изпълнени', 'изпълнени'), ('шпакловка/замазка', 'шпакловка/замазка')], max_length=20),
        ),
        migrations.AlterField(
            model_name='furnishingmodel',
            name='name',
            field=models.CharField(choices=[('обзаведен', 'обзаведен'), ('необзаведен', 'необзаведен')], max_length=20),
        ),
        migrations.AlterField(
            model_name='statusmodel',
            name='name',
            field=models.CharField(choices=[('активна обява', 'активна обява'), ('неактивна/продадено', 'неактивна/продадено')], max_length=20),
        ),
    ]
