# Generated by Django 3.2.4 on 2021-07-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart_app', '0012_auto_20210706_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
