# Generated by Django 3.2.4 on 2021-07-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart_app', '0013_alter_apartmentmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentmodel',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
