# Generated by Django 3.2.4 on 2021-07-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart_app', '0014_alter_apartmentmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentmodel',
            name='image_url',
        ),
        migrations.AddField(
            model_name='apartmentmodel',
            name='image',
            field=models.ImageField(default='', upload_to='aparts'),
            preserve_default=False,
        ),
    ]
