# Generated by Django 3.2.4 on 2021-07-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apart_app', '0015_auto_20210713_2141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApartModel',
        ),
    ]
