# Generated by Django 3.2.4 on 2021-07-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart_app', '0016_delete_apartmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentmodel',
            name='town',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
