# Generated by Django 3.2.4 on 2021-07-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart_app', '0019_alter_apartmentmodel_price_realized'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApartFilterModel',
        ),
        migrations.RemoveField(
            model_name='apartmentmodel',
            name='counter_seen',
        ),
        migrations.AlterField(
            model_name='typemodel',
            name='name',
            field=models.CharField(choices=[('Едностаен', 'Едностаен'), ('Двустаен', 'Двустаен'), ('Тристаен', 'Тристаен')], max_length=20),
        ),
    ]
