# Generated by Django 3.2.4 on 2021-07-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart_app', '0020_auto_20210720_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentmodel',
            name='contact_phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
