# Generated by Django 3.2.4 on 2021-07-21 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apart_app', '0023_alter_apartmentmodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.apartuser'),
            preserve_default=False,
        ),
    ]
