# Generated by Django 3.2.4 on 2021-07-25 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apart_app', '0024_apartmentmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentmodel',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apart_app.townmodel'),
        ),
    ]
