# Generated by Django 3.2.4 on 2021-07-25 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apart_app', '0025_alter_apartmentmodel_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentmodel',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apart_app.townmodel'),
        ),
        migrations.AlterField(
            model_name='townmodel',
            name='name',
            field=models.CharField(choices=[('Пловдив', 'Пловдив'), ('София', 'София'), ('София', 'Варна')], max_length=20),
        ),
    ]
