# Generated by Django 3.2.4 on 2021-07-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart_app', '0028_alter_apartmentmodel_construction_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentmodel',
            name='contact_phone',
            field=models.CharField(max_length=20),
        ),
    ]
