# Generated by Django 3.2.4 on 2021-08-07 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apart_app', '0029_alter_apartmentmodel_contact_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TownModel',
        ),
    ]
